version: "3"
services:
  web:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: mysql:8.0
    environment:
      - MARIADB_ROOT_PASSWORD=employerr
      - MARIADB_DATABASE=employerr
    ports:
      - "13306:13306"